export const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const MONTHS_BN = [
  'জানুয়ারি',
  'ফেব্রুয়ারি',
  'মার্চ',
  'এপ্রিল',
  'মে',
  'জুন',
  'জুলাই',
  'আগস্ট',
  'সেপ্টেম্বর',
  'অক্টোবর',
  'নভেম্বর',
  'ডিসেম্বর',
];

export const DAYS = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

export const DAYS_BN = [
  'সোমবার',
  'মঙ্গলবার',
  'বুধবার',
  'বৃহস্পতিবার',
  'শুক্রবার',
  'শনিবার',
  'রবিবার',
];

export const ALL_DESCRIPTIONS = [
  { icon: 'clearsky_day.svg', description: 'clearsky_day' },
  { icon: 'clearsky_night.svg', description: 'clearsky_night' },
  { icon: 'cloudy.svg', description: 'cloudy' },
  { icon: 'fair_day.svg', description: 'fair_day' },
  { icon: 'fair_night.svg', description: 'fair_night' },
  { icon: 'fog.svg', description: 'fog' },
  { icon: 'heavyrain.svg', description: 'heavyrain' },
  { icon: 'heavyrainandthunder.svg', description: 'heavyrainandthunder' },
  { icon: 'heavyrainshowers_day.svg', description: 'heavyrainshowers_day' },
  { icon: 'heavyrainshowers_night.svg', description: 'heavyrainshowers_night' },
  { icon: 'heavyrainshowersandthunder_day.svg', description: 'heavyrainshowersandthunder_day' },
  { icon: 'heavyrainshowersandthunder_night.svg', description: 'heavyrainshowersandthunder_night' },
  { icon: 'heavysleet.svg', description: 'heavysleet' },
  { icon: 'heavysleetandthunder.svg', description: 'heavysleetandthunder' },
  { icon: 'heavysleetshowers_day.svg', description: 'heavysleetshowers_day' },
  { icon: 'heavysleetshowers_night.svg', description: 'heavysleetshowers_night' },
  { icon: 'heavysleetshowersandthunder_day.svg', description: 'heavysleetshowersandthunder_day' },
  { icon: 'heavysleetshowersandthunder_night.svg', description: 'heavysleetshowersandthunder_night' },
  { icon: 'heavysnow.svg', description: 'heavysnow' },
  { icon: 'heavysnowandthunder.svg', description: 'heavysnowandthunder' },
  { icon: 'heavysnowshowers_day.svg', description: 'heavysnowshowers_day' },
  { icon: 'heavysnowshowers_night.svg', description: 'heavysnowshowers_night' },
  { icon: 'heavysnowshowersandthunder_day.svg', description: 'heavysnowshowersandthunder_day' },
  { icon: 'heavysnowshowersandthunder_night.svg', description: 'heavysnowshowersandthunder_night' },
  { icon: 'lightrain.svg', description: 'lightrain' },
  { icon: 'lightrainandthunder.svg', description: 'lightrainandthunder' },
  { icon: 'lightrainshowers_day.svg', description: 'lightrainshowers_day' },
  { icon: 'lightrainshowers_night.svg', description: 'lightrainshowers_night' },
  { icon: 'lightrainshowersandthunder_day.svg', description: 'lightrainshowersandthunder_day' },
  { icon: 'lightrainshowersandthunder_night.svg', description: 'lightrainshowersandthunder_night' },
  { icon: 'lightsleet.svg', description: 'lightsleet' },
  { icon: 'lightsleetandthunder.svg', description: 'lightsleetandthunder' },
  { icon: 'lightsleetshowers_day.svg', description: 'lightsleetshowers_day' },
  { icon: 'lightsleetshowers_night.svg', description: 'lightsleetshowers_night' },
  { icon: 'lightsleetshowersandthunder_day.svg', description: 'lightsleetshowersandthunder_day' },
  { icon: 'lightsleetshowersandthunder_night.svg', description: 'lightsleetshowersandthunder_night' },
  { icon: 'lightsnow.svg', description: 'lightsnow' },
  { icon: 'lightsnowandthunder.svg', description: 'lightsnowandthunder' },
  { icon: 'lightsnowshowers_day.svg', description: 'lightsnowshowers_day' },
  { icon: 'lightsnowshowers_night.svg', description: 'lightsnowshowers_night' },
  { icon: 'lightsnowshowersandthunder_day.svg', description: 'lightsnowshowersandthunder_day' },
  { icon: 'lightsnowshowersandthunder_night.svg', description: 'lightsnowshowersandthunder_night' },
  { icon: 'partlycloudy_day.svg', description: 'partlycloudy_day' },
  { icon: 'partlycloudy_night.svg', description: 'partlycloudy_night' },
  { icon: 'rain.svg', description: 'rain' },
  { icon: 'rainandthunder.svg', description: 'rainandthunder' },
  { icon: 'rainshowers_day.svg', description: 'rainshowers_day' },
  { icon: 'rainshowers_night.svg', description: 'rainshowers_night' },
  { icon: 'rainshowersandthunder_day.svg', description: 'rainshowersandthunder_day' },
  { icon: 'rainshowersandthunder_night.svg', description: 'rainshowersandthunder_night' },
  { icon: 'sleet.svg', description: 'sleet' },
  { icon: 'sleetandthunder.svg', description: 'sleetandthunder' },
  { icon: 'sleetshowers_day.svg', description: 'sleetshowers_day' },
  { icon: 'sleetshowers_night.svg', description: 'sleetshowers_night' },
  { icon: 'sleetshowersandthunder_day.svg', description: 'sleetshowersandthunder_day' },
  { icon: 'sleetshowersandthunder_night.svg', description: 'sleetshowersandthunder_night' },
  { icon: 'snow.svg', description: 'snow' },
  { icon: 'snowandthunder.svg', description: 'snowandthunder' },
  { icon: 'snowshowers_day.svg', description: 'snowshowers_day' },
  { icon: 'snowshowers_night.svg', description: 'snowshowers_night' },
  { icon: 'snowshowersandthunder_day.svg', description: 'snowshowersandthunder_day' },
  { icon: 'snowshowersandthunder_night.svg', description: 'snowshowersandthunder_night' },
  { icon: 'fog.svg', description: 'fog' },
  { icon: 'heavyrainshowers_day.svg', description: 'heavyrainshowers_day' },
  { icon: 'heavyrainshowers_night.svg', description: 'heavyrainshowers_night' }
]